### ISSUE TITLE
[pg.402] 글자 오류

### ISSUE THREAD

**Issue by xxzeroeight** [lleellee0/java-for-backend#13]
page.402에 handleEntityNotFoundExceptionException 메소드를 기존 GlobalExceptionHandler에 추가해야 하는데,

"EntityNotFoundException.java 중 일부"라고 적혀있어서 어디(EntityNotFoundException, GlobalExceptionHandler)에 추가해야되는지 헷갈릴 수 있을 것같습니다.

**Comment by lleellee0** [comment]
앗 그렇네요 ㅠㅠ 이 부분은 실수입니다.
