### ISSUE TITLE
[Tip]도커를 처음 사용하는 사람들이 겪는 프리징(멈춤) 현상 해결

### ISSUE THREAD

**Issue by zakard114** [lleellee0/java-for-backend#5]
이는 도커가 메모리 제어옵션을 설치시에 제공하지 않았기 때문으로, 이로인해 WSL이 메모리를 무한정 점유하게 된 결과이다. 도커 좌측 하단에 RAM부분의 수치가 2 또는 4기가를 넘어 7이나 8GB인 상태에서 흔히 발생하는 듯 하다. 다음과 같이 설정하면 RAM을 안정화 시켜 무리없이 도커 데스크탑을 이용할 수 있을 것이다. 

Window + R을 눌러 %USERPROFILE%을 입력한다.
파일 탐색기 경로 : (C:\Users\%USERNAME%) 여기서 USERNAME은 윈도우 설치시 사용자가 설정한 사용자 컴퓨터의 이름이다. 
해당 경로에 .wslconfig 을 만듦으로써 WSL 설정을 변경할 수 있다. 
만드는 방법은 우선 메모장에 아래 내용을 붙여넣기한 후, 아무이름으로 저장한다. 그리고 파일이름바꾸기를 해서 이름을 지우고 확장자 형식을 .txt에서 .wslconfig로 바꾼다.

[wsl2]
memory=2GB
processors=2
swap=1GB
localhostForwarding=true

wslconfig 파일을 적용하기위해, 
wsl --shutdown 명령어 또는 리부팅하면 적용된다.

이후 도커 데스크탑을 재가동시킨 후 화면 좌측 하단에 RAM이 설정한 수치(내 경우 2GB)이하로 유지됨을 알 수 있다.

출처: 

https://velog.io/@dailylifecoding/docker-desktop-make-my-computer-slow

https://velog.io/@alirz-pixel/wsl2-Vmmem-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%A0%90%EC%9C%A0%EC%9C%A8-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0

https://learn.microsoft.com/ko-kr/windows/wsl/wsl-config

**Comment by lleellee0** [comment]
@zakard114 

좋은 팁 감사합니다!!
환경에 따라 비슷한 이슈 겪는 분들도 있을 것 같은데, 좋은 참고가 될 것 같습니다~

**Comment by zakard114** [comment]
천만에요. ㅎ 
맞습니다. 저런거 겪으면 난감할 것 같아요. 가끔씩 프로그램들이 좀더 유저친화적이면 하는 생각이 듭니다.
