### ISSUE TITLE
[pg.577] ShortenUrlRepository 인터페이스에 @Repository누락 

### ISSUE THREAD

**Issue by zakard114** [lleellee0/java-for-backend#9]
ShortenUrlRepository 인터페이스 상단에 @Repository를 명시하여 IoC컨테이너에 빈(bean)으로 등록하지 않으면 pg.578의 생성자에 @Autowired가 되지 않는다.

**Comment by lleellee0** [comment]
해당 애너테이션은 p.584의 구현체에만 붙여줘도 될겁니다~
그 이전에는 원래 실행될 의도가 없었습니다. :)
